name: GitHub Actions Self-Introducing
run-name: ${{ github.actor }}'s SELF-INTRODUCING ğŸš€
on: [push]
jobs:
  SELF-INTRODUCING:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Hi! My name is taeheon."
      - run: echo "Today I join the github study class and my repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "This class is pretty difficult."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."